config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  scope "(:locale)", locale: /en|fr|de|fi/ do
    devise_for :users
    post 'authenticate', to: 'api_authentication#authenticate'
    concern :exportable, Blacklight::Routes::Exportable.new

    resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      concerns :exportable
    end

    resources :bookmarks do
      concerns :exportable

      collection do
        delete 'clear'
      end
    end

      concern :searchable, Blacklight::Routes::Searchable.new

    resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
      concerns :searchable
      concerns :range_searchable

    end

    concern :exportable, Blacklight::Routes::Exportable.new

    resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      concerns :exportable
    end

    resources :bookmarks do
      concerns :exportable

      collection do
        delete 'clear'
      end
    end

    mount Blacklight::Engine => '/'
    mount BlacklightAdvancedSearch::Engine => '/'
    # get 'advanced' => 'advanced#index'
    # get 'advanced/range_limit' => 'advanced#range_limit'


    get '/annotations/search', to: 'annotations#search'

    post '/annotations/add', to: 'annotations#add_annotation'

    get '/locales/:id/translation.json', to: 'assets#locale'

    get '/explore', to: 'catalog#explore'

    resources :feedbacks

    root to: "catalog#index"
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :datasets, :except => ['edit']

    post '/datasets/:id/delete_searches', to: 'datasets#delete_searches'
    post '/datasets/:id/rename', to: 'datasets#rename_dataset'
    post '/datasets/add', to: 'datasets#add'
    post '/datasets/create_and_add', to: 'datasets#create_and_add'
    post '/datasets/delete_elements', to: 'datasets#delete_elements'
    get '/datasets/rename_dataset_modal/:id', to: 'datasets#rename_dataset_modal'
    post '/datasets/apply_rename_dataset', to: 'datasets#apply_rename_dataset'

    get '/personal_research_assistant', to: 'personal_research_assistant#index'
    get '/personal_research_assistant/show_results/:task_uuid', to: 'personal_research_assistant#show_results'
    get '/personal_research_assistant/show_report/:task_uuid', to: 'personal_research_assistant#show_report'
    get '/personal_research_assistant/show_params/:task_uuid', to: 'personal_research_assistant#show_params'
    get '/personal_research_assistant/tm_show_results/:task_uuid', to: 'personal_research_assistant#tm_show_results'
    get '/personal_research_assistant/tm_show_params/:task_uuid', to: 'personal_research_assistant#tm_show_params'
    get '/personal_research_assistant/describe_topics/', to: 'personal_research_assistant#describe_topics'
    get '/personal_research_assistant/list_models', to: 'personal_research_assistant#list_models'
    post '/personal_research_assistant/tm_action', to: 'personal_research_assistant#tm_action'
    post '/personal_research_assistant/search', to: 'personal_research_assistant#search_task'
    post '/personal_research_assistant/create_search_task', to: 'personal_research_assistant#create_search_task'
    post '/personal_research_assistant/analyse', to: 'personal_research_assistant#analysis_task'
    post '/personal_research_assistant/investigate', to: 'personal_research_assistant#investigate_task'
    get '/update_tasks_status', to: 'personal_research_assistant#update_status'

    get '/personal_workspace/describe_search/:search_id', to: 'personal_workspace#describe_search'
    get '/personal_workspace/describe_dataset/:dataset_id', to: 'personal_workspace#describe_dataset'
    get '/personal_workspace/investigate_search/:search_id', to: 'personal_workspace#investigate_search'
    get '/personal_workspace/investigate_dataset/:dataset_id', to: 'personal_workspace#investigate_dataset'
    get '/personal_workspace/describe_search_modal/:run_uuid', to: 'personal_workspace#describe_search_modal'
    get '/personal_workspace/show/:task_id', to: 'personal_workspace#show'
    get '/personal_workspace/update_tasks', to: 'personal_workspace#update_tasks'
    get '/personal_workspace/update_experiments', to: 'personal_workspace#update_experiments'
    post '/personal_workspace/get_run_report', to: 'personal_workspace#get_run_report'
    post '/personal_workspace/get_task_report', to: 'personal_workspace#get_task_report'
    post '/personal_workspace/get_task_results', to: 'personal_workspace#get_task_results'
    post '/personal_workspace/query_task_results', to: 'personal_workspace#query_task_results'
    get '/personal_workspace/delete_task/:uuid', to: 'personal_workspace#delete_task'
    get '/personal_workspace/delete_experiment/:id', to: 'personal_workspace#delete_experiment'

    get '/personal_research_assistant/utilities', to: 'personal_research_assistant#get_utilities'
    post '/personal_research_assistant/user_tasks', to: 'personal_research_assistant#get_user_tasks'
    get '/personal_research_assistant/topic_models', to: 'personal_research_assistant#get_topic_models'
    post '/personal_research_assistant/render_utility', to: 'personal_research_assistant#render_utility'

    get '/topic_models', to: 'topic_models#index'
    get '/topic_models/describe_modal', to: 'topic_models#describe_tm_modal'
    get '/topic_models/visualize/:tm_name', to: 'topic_models#visualize_lda_modal'
    post '/topic_models/describe', to: 'topic_models#describe'
    get '/topic_models/query_modal/search/:search_id', to: 'topic_models#query_modal'
    get '/topic_models/query_modal/dataset/:dataset_id', to: 'topic_models#query_modal'
    post '/topic_models/query', to: 'topic_models#query'
    post '/topic_models/query_results', to: 'topic_models#query_results'

    get '/get_min_max_dates', to: 'catalog#get_min_max_dates'
    get '/search_help', to: 'catalog#help'
    get '/platform_help', to: 'catalog#platform_video'
    get '/kw_suggest', to: 'catalog#kw_suggest'
    post '/tools/query_embd_model', to: 'catalog#query_embd_model'
    post '/catalog/set_working_dataset', to: 'catalog#set_working_dataset'
    post '/catalog/confirm_modify_dataset', to: 'catalog#confirm_modify_dataset'
    post '/catalog/apply_modify_dataset', to: 'catalog#apply_modify_dataset'
    post '/catalog/modify_doc_relevancy', to: 'catalog#modify_doc_relevancy'
    post '/catalog/article_parts', to: 'catalog#article_parts'
    post '/catalog/linked_entity_search', to: 'catalog#linked_entity_search'
    post '/catalog/get_named_entities_kburl_label', to: 'catalog#get_named_entities_kburl_label'
    get '/get_locale', to: "catalog#get_locale"
    get '/random_samples_modal', to: 'catalog#random_samples_modal'
    get '/wide_date_histogram', to: 'catalog#wide_date_histogram'
    get '/add_all_docs_to_dataset_modal', to: 'catalog#add_all_docs_to_dataset'
    post '/add_query_to_dataset', to: 'catalog#add_query_to_dataset'
    post "/confirm_compound_article", to: "catalog#confirm_compound_article"
    post "/create_compound_article", to: "catalog#create_compound_article"
    post "/delete_compound_article", to: "catalog#delete_compound_article"
    post '/get_random_sample', to: 'catalog#get_random_sample'

    match '/stance_evol' => 'stance_evol#index', via: [:get, :post, :put, :patch, :delete]

    post "/saved_searches/save", to: "saved_searches#save"
    post "/saved_searches/confirm_save", to: "saved_searches#confirm_save"
    get "/saved_searches", to: "saved_searches#index"
    get "/saved_searches/get_ids/:id", to: "saved_searches#get_ids"
    get '/delete_search/:id', to: 'saved_searches#delete_search'
    get "/personal_workspace", to: "personal_workspace#index"
    get "/personal_workspace/create_experiment", to: "personal_workspace#create_experiment"

    post "/list_datasets", to: "api_base#list_datasets"
    post "/get_dataset_content", to: "api_base#get_dataset_content"
    post "/export_dataset/zipped", to: "export#zipped_export"
    post "/export_dataset/csv", to: "export#csv_export"
    post "/export_dataset/excel", to: "export#excel_export"
    post "/export_dataset/json", to: "export#json_export"
    get "/datasets_merge", to: "datasets#merge_dataset_modal"
    post "/datasets/apply_merge_dataset", to: "datasets#apply_merge_dataset"
    get "/create_subdataset", to: "datasets#subdataset_modal"
    post "/datasets/apply_subdataset", to: "datasets#apply_subdataset"
    post "/datasets/get_datasets_with_doc", to: "datasets#get_datasets_with_doc"
    post "/datasets/paginate", to: "datasets#paginate"
    post "/datasets/get_named_entities", to: "datasets#get_named_entities"

    get "/experiment/show/:id", to: "experiment#show"
    post "/experiment/add_data_source_modal", to: "experiment#add_data_source_modal"
    post "/experiment/add_data_source", to: "experiment#add_data_source"
    post "/experiment/save", to: "experiment#save"
    post "/experiment/load", to: "experiment#load"
    post "/experiment/get_run_id", to: "experiment#get_run_id"
    get "/experiment/new_experiment", to: "experiment#new_experiment"
    post "/experiment/add_output_modal", to: "experiment#add_output_modal"
    post "/experiment/explain", to: "experiment#explain_modal"
    post "/experiment/report", to: "experiment#report_modal"
    post "/experiment/run", to: "experiment#run_experiment"
    post "/experiment/get_status", to: "experiment#get_status"
    post "/save_dataset_from_experiment_modal", to: "experiment#convert_dataset_modal"
    post "/save_dataset_from_experiment", to: "experiment#convert_dataset"

  end

  mount Riiif::Engine => '/iiif', as: 'riiif'

  get '/get_stats', to: 'catalog#get_stats'
  get '/iiif/:id/manifest.json', to: 'iiif#manifest'
  get '/iiif/:id/annotated_manifest.json', to: 'iiif#manifest_with_annotations'
  get '/iiif/:id/list/:name', to: 'iiif#annotation_list'

app/views/catalog/_confirm_compound_article.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h3 class="modal-title" id="params_label">Create a new compound article</h3>
</div>

<div class="modal-body">

  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" href="#collapse_art_content">Overview of the article</a>
        </h4>
      </div>
      <div id="collapse_art_content" class="panel-collapse collapse">
        <div class="panel-body">
          <% article_parts.values.each do |part| %>
            <p><%= part["text"][1...-1].gsub("\\n", " ").html_safe %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <form id="create_compound_article_form" class="form-inline" novalidate="novalidate" data-remote="true" method='post' action="/create_compound_article">
    <div class="form-group">
      <label for="compound_title">Title:</label>
      <input type="text" name="compound_title" class="form-control" id="compound_title">
    </div>
    <input type="hidden" name="issue_id" value="<%= issue_id %>"/>
    <% article_parts.values.each do |part| %>
          <input type="hidden" name="parts[]" value="<%= part["id"] %>"/>
    <% end %>
    <button id="create_compound_form_button" type="submit" class="btn btn-primary" data-disable-with="Working..." style="float: right;">Create compound article</button>
  </form>


</div>
<div id="compound_log" class="modal-footer" style="display: none"></div>

<!--<div class="modal-footer">-->
<!--  <button type="button" class="btn" data-dismiss="modal">Cancel</button>-->
<!--  <form id="apply_dataset_global_changes" class="form-inline" novalidate="novalidate" data-remote="false" method='post' action="/catalog/apply_modify_dataset">-->
<!--    <input type="hidden" name="target_relevancy" value="<%#= @target_relevancy %>"/>-->
<!--    <input type="hidden" name="current_url" value="<%#= @current_url %>"/>-->
    <%# @relevancy_changes.values.map{|li| li.map{|l| l[0]}}.flatten.each do |doc_id| %>
<!--      <input type="hidden" name="docs[]" value="<%#= doc_id %>"/>-->
    <%# end %>
<!--    <button type="submit" class="btn btn-info" data-disable-with="Working...">Apply changes</button>-->
<!--  </form>-->
<!--</div>-->

app/views/catalog/_custom_date_facet.html.erb
<div id="date_pickers">
  <form>
    <div class="form-group">
      <label for="f[date_created_dtsi][from]">From</label>
      <input type="text" id="date_facet_from" name="f[date_created_dtsi][from]" autocomplete="off">
    </div>
    <div class="form-group">
      <label for="f[date_created_dtsi][to]">To</label>
      <input type="text" id="date_facet_to" name="f[date_created_dtsi][to]" autocomplete="off">
    </div>
    <%=
        params = search_state.params_for_search.except(:page)
        params[:f].delete :date_created_dtsi if params[:f]
        render_hash_as_hidden_fields(params)
    %>
    <div class="form-group">
      <button class="btn btn-default" type="submit" href="#">Limit</button>
    </div>
  </form>
</div>
<ul class="facet-values list-unstyled">
  <% paginator = facet_paginator(facet_field, display_facet) %>

  <%#= render_facet_limit_list paginator, facet_field.key %>

  <% unless paginator.last_page? || params[:action] == "facet" %>
    <li class="more_facets_link">
      <%= link_to t("more_#{field_name}_html", scope: 'blacklight.search.facets', default: :more_html, field_name: facet_field.label),
                  search_facet_path(id: facet_field.key), class: "more_facets_link" %>
    </li>
  <% end %>
</ul>

app/views/catalog/_datasets_handling.html.erb
<% if has_search_parameters? %>
    <div class="panel panel-default">
        <div class="panel-heading">Dataset membership</div>
    <div class="panel-body">
        <div>
            <p><%= link_to "Create a dataset", "/datasets/new" %> to add documents to.</p>
        </div>
        <% if current_user.datasets.first %>
            <div>
                <form autocomplete="off" novalidate="novalidate" data-remote="true" action="/catalog/set_working_dataset" accept-charset="UTF-8" method="post" class="form-inline">
                    <label for="dataset[id]">Working dataset:</label>
                    <select id="working_dataset_select" name="dataset[id]" class="form-control form-control-sm">
                        <%= session[:working_dataset] ||= current_user.datasets.first.id%>
                        <%= options_for_select(current_user.datasets.map{|d| ["#{d.title} (#{d.documents.size} docs)", d.id]}, session[:working_dataset]) %>
                    </select>
                </form>
            </div>
            <hr/>
        <% end %>
        <div id="dataset_handling_div" class="sidenav" style="margin-top: 20px;">
                <div class="form-check">
                    <label class="form-check-label" for="select_all_checkbox">Select all visible documents</label>
                    <input class="form-check-input" type="checkbox" value="" id="select_all_checkbox">
                </div>
                <div class="">
                    <form id="global_dataset_relevancy_form" class="form-inline" novalidate="novalidate" data-remote="true" method='post' action="/catalog/confirm_modify_dataset">

                        <div class="form-group">
                            <label for="global_dataset_relevancy">Relevancy</label>
                            <select name="global_dataset_relevancy" class="form-control form-control-sm">
                                <%= options_for_select [["Delete", -1],["Not relevant", 0],["Somewhat relevant",1],["Relevant",2],["Very relevant",3]] %>
                            </select>
                        </div>
                        <!-- Hidden fields are generated from JS catalog#index -->
                        <div class="form-group">
                            <button class="btn btn-default" type="submit" href="#" id="apply_global_dataset_changes">
                                Apply relevancy for all selected documents
                            </button>
                        </div>
                    </form>
                </div>

        </div>
    </div>
</div>

<% end %>

app/views/catalog/_datasets_handling_show.html.erb
<div>
  <p><%= link_to "Create a dataset", "/datasets/new" %> to add documents to.</p>
</div>
<% if current_user.datasets.first %>
  <div>
    <form autocomplete="off" novalidate="novalidate" data-remote="true" action="/catalog/set_working_dataset" accept-charset="UTF-8" method="post" class="form-inline">
      <label for="dataset[id]">Working dataset:</label>
      <select id="working_dataset_select" name="dataset[id]" class="form-control form-control-sm">
        <%= session[:working_dataset] ||= current_user.datasets.first.id%>
        <%= options_for_select(current_user.datasets.map{|d| ["#{d.title} (#{d.documents.size} docs)", d.id]}, session[:working_dataset]) %>
      </select>
    </form>
  </div>
  <hr/>

  <h4>Issue</h4>
  <div id="issue_in_datasets_list"></div>
  <div>
    <form autocomplete="off" novalidate="novalidate" data-remote="true" action="/catalog/modify_doc_relevancy" accept-charset="UTF-8" method="post" class="form-inline">
      <label for="specific_dataset_relevancy">Set relevancy towards <span class="working_dataset_span"><%= Dataset.find(session['working_dataset']).title %></span>: </label>
      <select name="specific_dataset_relevancy" class="form-control form-control-sm">
        <%= options_for_select [["Delete", -1],["Not relevant", 0],["Somewhat relevant",1],["Relevant",2],["Very relevant",3]] %>
      </select>
      <input type="hidden" name="doc_id" value="<%= @document.id %>"/>
      <input type="hidden" name="current_url" value="<%= request.original_url %>"/>
      <button class="specific_apply_relevancy btn btn-default" type="submit" href="#" data-disable-with="Working...">
        Apply
      </button>
    </form>
  </div>

    <div id="article_dataset_panel" style="display: none;">
        <hr/>
        <h4>Selected Article</h4>
        <div id="article_in_datasets_list"></div>
        <div>
            <form autocomplete="off" novalidate="novalidate" data-remote="true" action="/catalog/modify_doc_relevancy" accept-charset="UTF-8" method="post" class="form-inline">
                <label for="specific_dataset_relevancy">Set relevancy towards <span class="working_dataset_span"><%= Dataset.find(session['working_dataset']).title %></span>: </label>
                <select name="specific_dataset_relevancy" class="form-control form-control-sm">
                    <%= options_for_select [["Delete", -1],["Not relevant", 0],["Somewhat relevant",1],["Relevant",2],["Very relevant",3]] %>
                </select>
                <input type="hidden" name="doc_id" value=""/>
                <input type="hidden" name="current_url" value="<%= request.original_url %>"/>
                <button class="specific_apply_relevancy btn btn-default" type="submit" href="#" data-disable-with="Working...">
                    Apply
                </button>
            </form>
        </div>
    </div>

    <div id="compound_article_dataset_panel" style="display: none;">
        <hr/>
        <h4>Selected Compound Article</h4>
        <div id="compound_article_in_datasets_list"></div>
        <div>
            <form autocomplete="off" novalidate="novalidate" data-remote="true" action="/catalog/modify_doc_relevancy" accept-charset="UTF-8" method="post" class="form-inline">
                <label for="specific_dataset_relevancy">Set relevancy towards <span class="working_dataset_span"><%= Dataset.find(session['working_dataset']).title %></span>: </label>
                <select name="specific_dataset_relevancy" class="form-control form-control-sm">
                    <%= options_for_select [["Delete", -1],["Not relevant", 0],["Somewhat relevant",1],["Relevant",2],["Very relevant",3]] %>
                </select>
                <input type="hidden" name="doc_id" value=""/>
                <input type="hidden" name="current_url" value="<%= request.original_url %>"/>
                <input type="hidden" name="compound" value="true>"/>
                <input type="hidden" name="compound_title" value=""/>
                <button class="specific_apply_relevancy btn btn-default" type="submit" href="#" data-disable-with="Working...">
                    Apply
                </button>
            </form>
        </div>
    </div>
<% end %>

app/views/catalog/_home.html.erb
<% #Search form can be added here, defaulted to the navbar for Bootstrap version -%>
<%= image_tag "newseye_logo.png", size: '800x600' %>

app/views/catalog/_index_default.html.erb
<% doc_presenter = index_presenter(document) %> 
<%# default partial to display solr document fields in catalog index view -%>
<dl class="document-metadata dl-horizontal dl-invert col-md-8">
  
  <% index_fields(document).each do |field_name, field| -%>
    <% if should_render_index_field? document, field %>
	    <dt class="blacklight-<%= field_name.parameterize %>"><%= render_index_field_label document, field: field_name %></dt>
	    <dd class="blacklight-<%= field_name.parameterize %>"><%= doc_presenter.field_value field_name %></dd>
    <% end -%>
  <% end -%>

  <div class="dataset_info document_<%= document.id %>">
    <div class="in_datasets_list">
      <input type="checkbox" id="" class="dataset_check"/>
      <% in_datasets = current_user.datasets_with_doc(document.id) %>
      <% unless in_datasets.empty? %>
        <p>
          Currently belongs to:
          <% in_datasets.each do |dataset_id, dataset_title, relevancy| %>
            <% badge_type, tooltip = get_info_from_relevancy relevancy %>
            <%= link_to dataset_path(dataset_id) do %>
              <span class="dataset-<%= dataset_id %> badge badge-<%= badge_type %>" title="<%= tooltip %>" data-relevancy="<%= relevancy %>"><%= dataset_title %></span>
            <% end %>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>

  <% if document.solr_response[:highlighting] %>
    <% if document.solr_response[:highlighting][document[:id]] %>
      <% document.solr_response[:highlighting][document[:id]].keys.each do |hl_field| %>
        <% unless document.solr_response[:highlighting][document[:id]][hl_field].empty? %>
          <div class="panel-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                  <a href="#<%= document[:id] %>_extracts" data-toggle="collapse">See extracts</a>
                </h4>
              </div>

              <div id="<%= document[:id] %>_extracts" class="panel-collapse collapse">
                <ul class="list-group">
                  <% document.solr_response[:highlighting][document[:id]][hl_field].each do |extract| %>
                    <li class="list-group-item"><em>...<%= extract.gsub(/\n/,'<br/>').gsub('<br/><br/>','<br/>').html_safe %>...</em></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
          <% break %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</dl>

app/views/catalog/_index_header_default.html.erb
<%# header bar for doc items in index view -%>
<div class="documentHeader row">
  <%# main title container for doc partial view
      How many bootstrap columns need to be reserved
      for bookmarks control depends on size.
  -%>
  <% document_actions = capture do %>
    <% # bookmark functions for items/docs -%>
    <%#= render_index_doc_actions document, wrapping_class: "index-document-functions col-sm-3 col-lg-2" %>
  <% end %>

  <h3 class="index_title document-title-heading <%= document_actions.present? ? "col-sm-9 col-lg-10" : "col-md-12" %>">
    <% if counter = document_counter_with_offset(document_counter) %>
      <span class="document-counter">
        <%= t('blacklight.search.documents.counter', counter: counter) %>
      </span>
    <% end %>
    <%= link_to_document document, document_show_link_field(document), counter: counter %>
  </h3>

  <%= document_actions %>
</div>

app/views/catalog/_named_entities_panel.html.erb
<div id="named_entities_panels">
    <%# @named_entities = get_named_entities_for_doc(@document.id) %>
    <% linked_entities = get_linked_entities @named_entities.map{ |k,v| v.map{|label, mentions_solr| label } }.flatten %>
    <% mapping = {"PER": "Persons", "LOC": "Locations", "ORG": "Organizations", "HumanProd": "Human Productions"}.with_indifferent_access %>

    <div id="@named_entities" style="display: none" data-ne="<%= @named_entities.to_json %>"></div>
    <% @named_entities.keys.each do |ne_type| %>
        <% puts "done" %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" href="#entities_<%= ne_type %>">
                        <%= mapping[ne_type] %>
                        <span style="color: grey">
                (<%= @named_entities[ne_type].keys.size %> entities,
                            <%= @named_entities[ne_type].keys.map{ |nel| @named_entities[ne_type][nel].size }.reduce(:+) %> mentions)
              </span>
                    </a>
                </h4>
            </div>
            <div id="entities_<%= ne_type %>" class="panel-collapse collapse">
                <ul class="list-group">
                    <% sorted_entities = @named_entities[ne_type].keys.sort_by{|label| -@named_entities[ne_type][label].size } %>
                    <% sorted_entities.each do |label| %>
                        <% if linked_entities[label] %>
                            <li class="list-group-item">
                                <a data-toggle="collapse" href="#entities_<%= ne_type %>_<%= label %>"><%= label == "" ? "Unlinked #{mapping[ne_type]}" : linked_entities[label][:label] %></a>
                                (<%= @named_entities[ne_type][label].size %> mention<%= "s" if @named_entities[ne_type][label].size > 1 %>)
                                <% if !linked_entities[label].nil? and !linked_entities[label][:kb_url].nil? %>
                                    <%= link_to linked_entities[label][:kb_url], class: "pull-right", target: :_blank do %>
                                        <span class="glyphicon glyphicon-info-sign" style="color: black"></span>
                                    <% end %>
                                <% end %>
                            </li>
                            <div id="entities_<%= ne_type %>_<%= label %>" class="panel-collapse collapse">
                                <ul class="list-group">
                                    <% @named_entities[ne_type][label].each do |ne| %>
                                        <li class="list-group-item ne_mention">
                                            &emsp;<%= ne['mention_ssi'] %>
                                            <% case ne['stance_fsi'] %>
                                            <% when -1 %>
                                                (-)
                                            <% when 0 %>
                                                (=)
                                            <% when 1 %>
                                                (+)
                                            <% end %>
                                        </li>
                                    <% end %>
                                </ul>
                            </div>
                        <% end %>
                    <% end %>
                </ul>
            </div>
        </div>

    <% end %>
</div>

app/views/catalog/_search_form.html.erb
<%= form_tag search_action_url, method: :get, class: 'search-query-form clearfix navbar-form', role: 'search' do %>
    <%= render_hash_as_hidden_fields(search_state.params_for_search.except(:q, :search_field, :qt, :page, :utf8)) %>
    <div class="input-group col-md-9">
        <% if search_fields.length > 1 %>
          <span class="input-group-addon for-search-field">
            <label for="search_field" class="sr-only"><%= t('blacklight.search.form.search_field.label') %></label>
              <% selected_value = params[:search_field] || "exact_search" %>
              <%= select_tag(:search_field, options_for_select(search_fields, h(selected_value)), title: t('blacklight.search.form.search_field.title'), id: "search_field", class: "search_field") %>
          </span>
        <% elsif search_fields.length == 1 %>
            <%= hidden_field_tag :search_field, search_fields.first.last %>
        <% end %>
        <label for="q" class="sr-only"><%= t('blacklight.search.form.search.label') %></label>
        <%= text_field_tag :q, params[:q], placeholder: t('blacklight.search.form.search.placeholder'), class: "search_q q form-control", id: "q", autofocus: should_autofocus_on_search_box?, data: {autocomplete_enabled: autocomplete_enabled?, autocomplete_path: blacklight.suggest_index_path} %>

        <span class="input-group-btn">
              <button type="submit" class="btn btn-primary search-btn" id="search">
                <span class="submit-search-text"><%= t('blacklight.search.form.submit') %></span>
                <span class="glyphicon glyphicon-search"></span>
              </button>
              <button class="btn btn-primary" type="button" href="#" id="help_modal" role="button">
                <span class="glyphicon glyphicon-question-sign"></span>
              </button>
            </span>
    </div>
<% end %>
<button class="btn btn-primary pull-right" type="button" href="#" id="kw_suggest_modal" role="button">
    Suggest keywords
</button>

<!--    <span id="doctype_selection">-->
<!--        <label>Search for:</label>-->
<!--        <span class="btn-group">-->
<!--            <button type="button" class="btn btn-default">Articles</button>-->
<!--            <button type="button" class="btn btn-default">Issues</button>-->
<!--            <button type="button" class="btn btn-default">Both</button>-->
<!--        </span>-->
<!--    </span>-->